  title: Christian Brickhouse
  markdown: kramdown
  permalink: /weblog/:year/:month/:day/:title
  theme: minima
  author: Christian Brickhouse
  email: me@christianbrickhouse.com
  show_excerpts: true
  github_username: chrisbrickhouse
  git_repo: chrisbrickhouse.github.io
  twitter_username: iamabrickhouse
  mastodon:
  - username: iamabrickhouse
    instance: fosstodon.org
  header_pages:
    - about/index.md
    - games/index.md

  defaults:
    - 
      scope: 
        path: "_posts"
      values:
        layout: "post"
        author: "Christian Brickhouse"
